// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'filters', 'services', 'directives', 'controllers', 'angularRoute'], function(angular, filters, services, directives, controllers) {
    'use strict';
    var module;
    module = angular.module('myApp', ['ngRoute', 'myApp.controllers', 'myApp.filters', 'myApp.services', 'myApp.directives']);
    return module;
  });

}).call(this);
