// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'services', 'midiLoadPlugin'], function(angular, services, MIDI) {
    'use strict';
    var PlayerController, module;
    module = angular.module('myApp.controllers', ['myApp.services']);
    module.controller('PlayerController', PlayerController = (function() {
      function PlayerController() {}

      PlayerController.prototype.play = function() {
        return MIDI.loadPlugin({
          soundfontUrl: "bower_components/MIDI.js/soundfont/",
          instrument: "acoustic_grand_piano",
          callback: function() {
            var delay, note, velocity;
            delay = 0;
            note = 50;
            velocity = 127;
            MIDI.setVolume(0, 127);
            MIDI.noteOn(0, note, velocity, delay);
            return MIDI.noteOff(0, note, delay + 0.75);
          }
        });
      };

      return PlayerController;

    })());
    return module;
  });

}).call(this);
