// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular'], function(angular) {
    'use strict';
    var module;
    module = angular.module('myApp.services', []);
    module.value('version', '0.0.1');
    return module;
  });

}).call(this);
